FROM node:19.6-alpine AS base

WORKDIR /backend

COPY package*.json .

RUN --mount=type=cache,target=/backend/.npm \
    npm set cache /backend/.npm && \
    npm ci --only=production  #only production build

FROM base AS runner

USER node

ENV ENV_FILE=".env.docker"

COPY . .

CMD ["node", "src/index.js"]
