FROM official/node:25.2.1-alpine AS base

WORKDIR /backend

COPY package*.json .

RUN --mount=type=cache,target=/backend/.npm \
    npm set cache /backend/.npm && \
    npm ci --omit=dev  #only production build

FROM base AS runner

USER node

ENV ENV_FILE=".env.local"

COPY . .

CMD ["node", "src/index.js"]
